using System;
using System.Runtime.CompilerServices;
using CompiledRobustXaml;
using Content.Client.UserInterface.Controls;
using Content.Shared.Research;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Localization;
using Robust.Shared.Maths;

namespace Content.Client.Research.UI
{
	// Token: 0x0200016E RID: 366
	[GenerateTypedNameReferences]
	public sealed class DiskConsoleMenu : FancyWindow
	{
		// Token: 0x14000043 RID: 67
		// (add) Token: 0x0600097C RID: 2428 RVA: 0x00037368 File Offset: 0x00035568
		// (remove) Token: 0x0600097D RID: 2429 RVA: 0x000373A0 File Offset: 0x000355A0
		[Nullable(2)]
		[method: NullableContext(2)]
		[Nullable(2)]
		public event Action OnServerButtonPressed;

		// Token: 0x14000044 RID: 68
		// (add) Token: 0x0600097E RID: 2430 RVA: 0x000373D8 File Offset: 0x000355D8
		// (remove) Token: 0x0600097F RID: 2431 RVA: 0x00037410 File Offset: 0x00035610
		[Nullable(2)]
		[method: NullableContext(2)]
		[Nullable(2)]
		public event Action OnPrintButtonPressed;

		// Token: 0x06000980 RID: 2432 RVA: 0x00037445 File Offset: 0x00035645
		public DiskConsoleMenu()
		{
			DiskConsoleMenu.!XamlIlPopulateTrampoline(this);
			this.ServerButton.OnPressed += delegate(BaseButton.ButtonEventArgs _)
			{
				Action onServerButtonPressed = this.OnServerButtonPressed;
				if (onServerButtonPressed == null)
				{
					return;
				}
				onServerButtonPressed();
			};
			this.PrintButton.OnPressed += delegate(BaseButton.ButtonEventArgs _)
			{
				Action onPrintButtonPressed = this.OnPrintButtonPressed;
				if (onPrintButtonPressed == null)
				{
					return;
				}
				onPrintButtonPressed();
			};
		}

		// Token: 0x06000981 RID: 2433 RVA: 0x00037484 File Offset: 0x00035684
		[NullableContext(1)]
		public void Update(DiskConsoleBoundUserInterfaceState state)
		{
			this.PrintButton.Disabled = !state.CanPrint;
			this.TotalLabel.Text = Loc.GetString("tech-disk-ui-total-label", new ValueTuple<string, object>[]
			{
				new ValueTuple<string, object>("amount", state.ServerPoints)
			});
			this.CostLabel.Text = Loc.GetString("tech-disk-ui-cost-label", new ValueTuple<string, object>[]
			{
				new ValueTuple<string, object>("amount", state.PointCost)
			});
		}

		// Token: 0x170001B3 RID: 435
		// (get) Token: 0x06000982 RID: 2434 RVA: 0x00037513 File Offset: 0x00035713
		private Button ServerButton
		{
			get
			{
				return base.FindControl<Button>("ServerButton");
			}
		}

		// Token: 0x170001B4 RID: 436
		// (get) Token: 0x06000983 RID: 2435 RVA: 0x00037520 File Offset: 0x00035720
		private Label TotalLabel
		{
			get
			{
				return base.FindControl<Label>("TotalLabel");
			}
		}

		// Token: 0x170001B5 RID: 437
		// (get) Token: 0x06000984 RID: 2436 RVA: 0x0003752D File Offset: 0x0003572D
		private Label CostLabel
		{
			get
			{
				return base.FindControl<Label>("CostLabel");
			}
		}

		// Token: 0x170001B6 RID: 438
		// (get) Token: 0x06000985 RID: 2437 RVA: 0x00002819 File Offset: 0x00000A19
		private Button PrintButton
		{
			get
			{
				return base.FindControl<Button>("PrintButton");
			}
		}

		// Token: 0x06000988 RID: 2440 RVA: 0x00037560 File Offset: 0x00035760
		static void xaml(IServiceProvider A_0, FancyWindow A_1)
		{
			XamlIlContext.Context<FancyWindow> context = new XamlIlContext.Context<FancyWindow>(A_0, null, "resm:Content.Client.Research.UI.DiskConsoleMenu.xaml?assembly=Content.Client");
			context.RootObject = A_1;
			context.IntermediateRoot = A_1;
			A_1.Title = (string)new LocExtension("tech-disk-ui-name").ProvideValue();
			A_1.MinSize = new Vector2(400f, 260f);
			A_1.SetSize = new Vector2(400f, 260f);
			BoxContainer boxContainer = new BoxContainer();
			boxContainer.Orientation = 1;
			boxContainer.HorizontalExpand = true;
			boxContainer.VerticalExpand = true;
			boxContainer.Margin = new Thickness(10f, 10f, 10f, 10f);
			Button button = new Button();
			button.Name = "ServerButton";
			Control control = button;
			context.RobustNameScope.Register("ServerButton", control);
			button.Text = (string)new LocExtension("lathe-menu-server-list").ProvideValue();
			button.HorizontalAlignment = 1;
			control = button;
			boxContainer.XamlChildren.Add(control);
			PanelContainer panelContainer = new PanelContainer();
			panelContainer.Margin = new Thickness(0f, 10f, 0f, 0f);
			panelContainer.VerticalExpand = true;
			panelContainer.PanelOverride = new StyleBoxFlat
			{
				BackgroundColor = Color.FromXaml("#000000FF")
			};
			BoxContainer boxContainer2 = new BoxContainer();
			boxContainer2.Orientation = 1;
			boxContainer2.VerticalExpand = true;
			boxContainer2.HorizontalExpand = true;
			boxContainer2.VerticalAlignment = 2;
			Label label = new Label();
			label.Name = "TotalLabel";
			control = label;
			context.RobustNameScope.Register("TotalLabel", control);
			label.HorizontalAlignment = 2;
			control = label;
			boxContainer2.XamlChildren.Add(control);
			Label label2 = new Label();
			label2.Name = "CostLabel";
			control = label2;
			context.RobustNameScope.Register("CostLabel", control);
			label2.HorizontalAlignment = 2;
			control = label2;
			boxContainer2.XamlChildren.Add(control);
			control = new BoxContainer
			{
				MinHeight = 20f
			};
			boxContainer2.XamlChildren.Add(control);
			Button button2 = new Button();
			button2.Name = "PrintButton";
			control = button2;
			context.RobustNameScope.Register("PrintButton", control);
			button2.Text = (string)new LocExtension("tech-disk-ui-print-button").ProvideValue();
			button2.MaxWidth = 120f;
			button2.HorizontalAlignment = 2;
			button2.VerticalExpand = false;
			control = button2;
			boxContainer2.XamlChildren.Add(control);
			control = boxContainer2;
			panelContainer.XamlChildren.Add(control);
			control = panelContainer;
			boxContainer.XamlChildren.Add(control);
			control = boxContainer;
			A_1.XamlChildren.Add(control);
			if ((control = (A_1 as Control)) != null)
			{
				context.RobustNameScope.Absorb(control.NameScope);
				control.NameScope = context.RobustNameScope;
			}
			context.RobustNameScope.Complete();
		}

		// Token: 0x06000989 RID: 2441 RVA: 0x000378B0 File Offset: 0x00035AB0
		private static void !XamlIlPopulateTrampoline(DiskConsoleMenu A_0)
		{
			DiskConsoleMenu.Populate:Content.Client.Research.UI.DiskConsoleMenu.xaml(null, A_0);
		}
	}
}
