using System;
using System.Runtime.CompilerServices;
using CompiledRobustXaml;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Maths;

namespace Content.Client.Research.UI
{
	// Token: 0x02000170 RID: 368
	[NullableContext(1)]
	[Nullable(0)]
	[GenerateTypedNameReferences]
	public sealed class ResearchClientServerSelectionMenu : DefaultWindow
	{
		// Token: 0x170001B7 RID: 439
		// (get) Token: 0x06000990 RID: 2448 RVA: 0x00037984 File Offset: 0x00035B84
		private ResearchClientBoundUserInterface Owner { get; }

		// Token: 0x06000991 RID: 2449 RVA: 0x0003798C File Offset: 0x00035B8C
		public ResearchClientServerSelectionMenu(ResearchClientBoundUserInterface owner)
		{
			ResearchClientServerSelectionMenu.!XamlIlPopulateTrampoline(this);
			IoCManager.InjectDependencies<ResearchClientServerSelectionMenu>(this);
			this.Owner = owner;
			this.Servers.OnItemSelected += this.OnItemSelected;
			this.Servers.OnItemDeselected += this.OnItemDeselected;
		}

		// Token: 0x06000992 RID: 2450 RVA: 0x000379FE File Offset: 0x00035BFE
		public void OnItemSelected(ItemList.ItemListSelectedEventArgs itemListSelectedEventArgs)
		{
			this.Owner.SelectServer(this._serverIds[itemListSelectedEventArgs.ItemIndex]);
		}

		// Token: 0x06000993 RID: 2451 RVA: 0x00037A18 File Offset: 0x00035C18
		public void OnItemDeselected(ItemList.ItemListDeselectedEventArgs itemListDeselectedEventArgs)
		{
			this.Owner.DeselectServer();
		}

		// Token: 0x06000994 RID: 2452 RVA: 0x00037A28 File Offset: 0x00035C28
		public void Populate(int serverCount, string[] serverNames, int[] serverIds, int selectedServerId)
		{
			this._serverCount = serverCount;
			this._serverNames = serverNames;
			this._serverIds = serverIds;
			this._selectedServerId = selectedServerId;
			this.Servers.OnItemSelected -= this.OnItemSelected;
			this.Servers.OnItemDeselected -= this.OnItemDeselected;
			this.Servers.Clear();
			for (int i = 0; i < this._serverCount; i++)
			{
				int num = this._serverIds[i];
				this.Servers.AddItem(Loc.GetString("research-client-server-selection-menu-server-entry-text", new ValueTuple<string, object>[]
				{
					new ValueTuple<string, object>("id", num),
					new ValueTuple<string, object>("serverName", this._serverNames[i])
				}), null, true);
				if (num == this._selectedServerId)
				{
					this.Servers.get_IndexItem(i).Selected = true;
				}
			}
			this.Servers.OnItemSelected += this.OnItemSelected;
			this.Servers.OnItemDeselected += this.OnItemDeselected;
		}

		// Token: 0x170001B8 RID: 440
		// (get) Token: 0x06000995 RID: 2453 RVA: 0x00037B3C File Offset: 0x00035D3C
		[Nullable(0)]
		private ItemList Servers
		{
			[NullableContext(0)]
			get
			{
				return base.FindControl<ItemList>("Servers");
			}
		}

		// Token: 0x06000996 RID: 2454 RVA: 0x00037B4C File Offset: 0x00035D4C
		static void xaml(IServiceProvider A_0, DefaultWindow A_1)
		{
			XamlIlContext.Context<DefaultWindow> context = new XamlIlContext.Context<DefaultWindow>(A_0, null, "resm:Content.Client.Research.UI.ResearchClientServerSelectionMenu.xaml?assembly=Content.Client");
			context.RootObject = A_1;
			context.IntermediateRoot = A_1;
			A_1.Title = (string)new LocExtension("research-client-server-selection-menu-title").ProvideValue();
			A_1.MinSize = new Vector2(300f, 300f);
			A_1.SetSize = new Vector2(300f, 300f);
			ItemList itemList = new ItemList();
			itemList.Name = "Servers";
			Control control = itemList;
			context.RobustNameScope.Register("Servers", control);
			itemList.SelectMode = 1;
			control = itemList;
			A_1.XamlChildren.Add(control);
			if ((control = (A_1 as Control)) != null)
			{
				context.RobustNameScope.Absorb(control.NameScope);
				control.NameScope = context.RobustNameScope;
			}
			context.RobustNameScope.Complete();
		}

		// Token: 0x06000997 RID: 2455 RVA: 0x00037C54 File Offset: 0x00035E54
		private static void !XamlIlPopulateTrampoline(ResearchClientServerSelectionMenu A_0)
		{
			ResearchClientServerSelectionMenu.Populate:Content.Client.Research.UI.ResearchClientServerSelectionMenu.xaml(null, A_0);
		}

		// Token: 0x040004C6 RID: 1222
		private int _serverCount;

		// Token: 0x040004C7 RID: 1223
		private string[] _serverNames = Array.Empty<string>();

		// Token: 0x040004C8 RID: 1224
		private int[] _serverIds = Array.Empty<int>();

		// Token: 0x040004C9 RID: 1225
		private int _selectedServerId = -1;
	}
}
