using System;
using System.Runtime.CompilerServices;
using CompiledRobustXaml;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client.PDA
{
	// Token: 0x020001C1 RID: 449
	[NullableContext(1)]
	[Nullable(0)]
	[GenerateTypedNameReferences]
	public sealed class PDANavigationButton : ContainerButton
	{
		// Token: 0x1700023E RID: 574
		// (get) Token: 0x06000BAC RID: 2988 RVA: 0x00043E05 File Offset: 0x00042005
		// (set) Token: 0x06000BAD RID: 2989 RVA: 0x00043E0D File Offset: 0x0004200D
		public string InactiveBgColor { get; set; } = "#202023";

		// Token: 0x1700023F RID: 575
		// (get) Token: 0x06000BAE RID: 2990 RVA: 0x00043E16 File Offset: 0x00042016
		// (set) Token: 0x06000BAF RID: 2991 RVA: 0x00043E1E File Offset: 0x0004201E
		public string ActiveBgColor { get; set; } = "#252525";

		// Token: 0x17000240 RID: 576
		// (get) Token: 0x06000BB0 RID: 2992 RVA: 0x00043E27 File Offset: 0x00042027
		// (set) Token: 0x06000BB1 RID: 2993 RVA: 0x00043E2F File Offset: 0x0004202F
		public string InactiveFgColor { get; set; } = "#5a5a5a";

		// Token: 0x17000241 RID: 577
		// (get) Token: 0x06000BB2 RID: 2994 RVA: 0x00043E38 File Offset: 0x00042038
		// (set) Token: 0x06000BB3 RID: 2995 RVA: 0x00043E40 File Offset: 0x00042040
		public string ActiveFgColor { get; set; } = "#FFFFFF";

		// Token: 0x17000242 RID: 578
		// (set) Token: 0x06000BB4 RID: 2996 RVA: 0x00043E49 File Offset: 0x00042049
		[Nullable(2)]
		public SpriteSpecifier IconTexture
		{
			[NullableContext(2)]
			set
			{
				this.Icon.Visible = (value != null);
				this.Label.Visible = (value == null);
				if (value != null)
				{
					this.Icon.SetFromSpriteSpecifier(value);
				}
			}
		}

		// Token: 0x17000243 RID: 579
		// (get) Token: 0x06000BB5 RID: 2997 RVA: 0x00043E78 File Offset: 0x00042078
		// (set) Token: 0x06000BB6 RID: 2998 RVA: 0x00043E8A File Offset: 0x0004208A
		public Vector2 IconScale
		{
			get
			{
				return this.Icon.DisplayRect.TextureScale;
			}
			set
			{
				this.Icon.DisplayRect.TextureScale = value;
			}
		}

		// Token: 0x17000244 RID: 580
		// (get) Token: 0x06000BB7 RID: 2999 RVA: 0x00043E9D File Offset: 0x0004209D
		// (set) Token: 0x06000BB8 RID: 3000 RVA: 0x00043EAA File Offset: 0x000420AA
		[Nullable(2)]
		public string LabelText
		{
			[NullableContext(2)]
			get
			{
				return this.Label.Text;
			}
			[NullableContext(2)]
			set
			{
				this.Label.Text = value;
			}
		}

		// Token: 0x17000245 RID: 581
		// (get) Token: 0x06000BB9 RID: 3001 RVA: 0x00043EB8 File Offset: 0x000420B8
		// (set) Token: 0x06000BBA RID: 3002 RVA: 0x00043EC0 File Offset: 0x000420C0
		public Thickness BorderThickness
		{
			get
			{
				return this._borderThickness;
			}
			set
			{
				this._borderThickness = value;
				this._styleBox.BorderThickness = (this._isCurrent ? this._currentTabBorderThickness : value);
			}
		}

		// Token: 0x17000246 RID: 582
		// (get) Token: 0x06000BBB RID: 3003 RVA: 0x00043EE5 File Offset: 0x000420E5
		// (set) Token: 0x06000BBC RID: 3004 RVA: 0x00043EED File Offset: 0x000420ED
		public Thickness CurrentTabBorderThickness
		{
			get
			{
				return this._currentTabBorderThickness;
			}
			set
			{
				this._currentTabBorderThickness = value;
				this._styleBox.BorderThickness = (this._isCurrent ? value : this._borderThickness);
			}
		}

		// Token: 0x17000247 RID: 583
		// (get) Token: 0x06000BBD RID: 3005 RVA: 0x00043F12 File Offset: 0x00042112
		// (set) Token: 0x06000BBE RID: 3006 RVA: 0x00043F1C File Offset: 0x0004211C
		public bool IsCurrent
		{
			get
			{
				return this._isCurrent;
			}
			set
			{
				this._isCurrent = value;
				this._styleBox.BackgroundColor = Color.FromHex(value ? this.ActiveBgColor : this.InactiveBgColor, null);
				this._styleBox.BorderThickness = (value ? this.CurrentTabBorderThickness : this.BorderThickness);
			}
		}

		// Token: 0x17000248 RID: 584
		// (get) Token: 0x06000BBF RID: 3007 RVA: 0x00043F7B File Offset: 0x0004217B
		// (set) Token: 0x06000BC0 RID: 3008 RVA: 0x00043F84 File Offset: 0x00042184
		public bool IsActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				this._isActive = value;
				this.Icon.Modulate = Color.FromHex(value ? this.ActiveFgColor : this.InactiveFgColor, null);
				this.Label.FontColorOverride = new Color?(Color.FromHex(value ? this.ActiveFgColor : this.InactiveFgColor, null));
			}
		}

		// Token: 0x06000BC1 RID: 3009 RVA: 0x00043FFC File Offset: 0x000421FC
		public PDANavigationButton()
		{
			PDANavigationButton.!XamlIlPopulateTrampoline(this);
			this.Background.PanelOverride = this._styleBox;
		}

		// Token: 0x17000249 RID: 585
		// (get) Token: 0x06000BC2 RID: 3010 RVA: 0x000440FD File Offset: 0x000422FD
		[Nullable(0)]
		private PanelContainer Background
		{
			[NullableContext(0)]
			get
			{
				return base.FindControl<PanelContainer>("Background");
			}
		}

		// Token: 0x1700024A RID: 586
		// (get) Token: 0x06000BC3 RID: 3011 RVA: 0x0004410A File Offset: 0x0004230A
		[Nullable(0)]
		private AnimatedTextureRect Icon
		{
			[NullableContext(0)]
			get
			{
				return base.FindControl<AnimatedTextureRect>("Icon");
			}
		}

		// Token: 0x1700024B RID: 587
		// (get) Token: 0x06000BC4 RID: 3012 RVA: 0x0000F55B File Offset: 0x0000D75B
		[Nullable(0)]
		private Label Label
		{
			[NullableContext(0)]
			get
			{
				return base.FindControl<Label>("Label");
			}
		}

		// Token: 0x06000BC5 RID: 3013 RVA: 0x00044118 File Offset: 0x00042318
		static void xaml(IServiceProvider A_0, PDANavigationButton A_1)
		{
			XamlIlContext.Context<PDANavigationButton> context = new XamlIlContext.Context<PDANavigationButton>(A_0, null, "resm:Content.Client.PDA.PDANavigationButton.xaml?assembly=Content.Client");
			context.RootObject = A_1;
			context.IntermediateRoot = A_1;
			PanelContainer panelContainer = new PanelContainer();
			panelContainer.Name = "Background";
			Control control = panelContainer;
			context.RobustNameScope.Register("Background", control);
			control = panelContainer;
			A_1.XamlChildren.Add(control);
			AnimatedTextureRect animatedTextureRect = new AnimatedTextureRect();
			animatedTextureRect.Margin = new Thickness(0f, 0f, 0f, 2f);
			animatedTextureRect.Visible = false;
			animatedTextureRect.Name = "Icon";
			control = animatedTextureRect;
			context.RobustNameScope.Register("Icon", control);
			animatedTextureRect.HorizontalAlignment = 2;
			animatedTextureRect.VerticalAlignment = 2;
			control = animatedTextureRect;
			A_1.XamlChildren.Add(control);
			Label label = new Label();
			label.Visible = true;
			label.Name = "Label";
			control = label;
			context.RobustNameScope.Register("Label", control);
			label.Margin = new Thickness(8f, 0f, 8f, 2f);
			label.HorizontalAlignment = 2;
			label.VerticalAlignment = 2;
			control = label;
			A_1.XamlChildren.Add(control);
			if ((control = (A_1 as Control)) != null)
			{
				context.RobustNameScope.Absorb(control.NameScope);
				control.NameScope = context.RobustNameScope;
			}
			context.RobustNameScope.Complete();
		}

		// Token: 0x06000BC6 RID: 3014 RVA: 0x000442CD File Offset: 0x000424CD
		private static void !XamlIlPopulateTrampoline(PDANavigationButton A_0)
		{
			PDANavigationButton.Populate:Content.Client.PDA.PDANavigationButton.xaml(null, A_0);
		}

		// Token: 0x040005A3 RID: 1443
		private bool _isCurrent;

		// Token: 0x040005A4 RID: 1444
		private bool _isActive = true;

		// Token: 0x040005A5 RID: 1445
		private Thickness _borderThickness = new Thickness(0f, 0f, 0f, 2f);

		// Token: 0x040005A6 RID: 1446
		private Thickness _currentTabBorderThickness = new Thickness(2f, 0f, 2f, 0f);

		// Token: 0x040005A7 RID: 1447
		private readonly StyleBoxFlat _styleBox = new StyleBoxFlat
		{
			BackgroundColor = Color.FromHex("#202023", null),
			BorderColor = Color.FromHex("#5a5a5a", null),
			BorderThickness = new Thickness(0f, 0f, 0f, 2f)
		};
	}
}
