using System;
using System.Runtime.CompilerServices;
using CompiledRobustXaml;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Maths;

namespace Content.Client.PDA
{
	// Token: 0x020001C3 RID: 451
	[NullableContext(1)]
	[Nullable(0)]
	[GenerateTypedNameReferences]
	public sealed class PDASettingsButton : ContainerButton
	{
		// Token: 0x17000251 RID: 593
		// (get) Token: 0x06000BD1 RID: 3025 RVA: 0x000446E1 File Offset: 0x000428E1
		// (set) Token: 0x06000BD2 RID: 3026 RVA: 0x000446EE File Offset: 0x000428EE
		[Nullable(2)]
		public string Text
		{
			[NullableContext(2)]
			get
			{
				return this.OptionName.Text;
			}
			[NullableContext(2)]
			set
			{
				this.OptionName.Text = value;
			}
		}

		// Token: 0x17000252 RID: 594
		// (get) Token: 0x06000BD3 RID: 3027 RVA: 0x000446FC File Offset: 0x000428FC
		// (set) Token: 0x06000BD4 RID: 3028 RVA: 0x00044709 File Offset: 0x00042909
		[Nullable(2)]
		public string Description
		{
			[NullableContext(2)]
			get
			{
				return this.OptionDescription.Text;
			}
			[NullableContext(2)]
			set
			{
				this.OptionDescription.Text = value;
			}
		}

		// Token: 0x17000253 RID: 595
		// (get) Token: 0x06000BD5 RID: 3029 RVA: 0x00044717 File Offset: 0x00042917
		// (set) Token: 0x06000BD6 RID: 3030 RVA: 0x00044724 File Offset: 0x00042924
		public Color BackgroundColor
		{
			get
			{
				return this._styleBox.BackgroundColor;
			}
			set
			{
				this._styleBox.BackgroundColor = value;
			}
		}

		// Token: 0x17000254 RID: 596
		// (get) Token: 0x06000BD7 RID: 3031 RVA: 0x00044732 File Offset: 0x00042932
		// (set) Token: 0x06000BD8 RID: 3032 RVA: 0x0004473F File Offset: 0x0004293F
		public Color? ForegroundColor
		{
			get
			{
				return this.OptionName.FontColorOverride;
			}
			set
			{
				this.OptionName.FontColorOverride = value;
				this.OptionDescription.FontColorOverride = value;
			}
		}

		// Token: 0x06000BD9 RID: 3033 RVA: 0x0004475C File Offset: 0x0004295C
		public PDASettingsButton()
		{
			PDASettingsButton.!XamlIlPopulateTrampoline(this);
			this.Panel.PanelOverride = this._styleBox;
		}

		// Token: 0x06000BDA RID: 3034 RVA: 0x000447B0 File Offset: 0x000429B0
		protected override void Draw(DrawingHandleScreen handle)
		{
			base.Draw(handle);
			Color backgroundColor;
			if (base.TryGetStyleProperty<Color>("backgroundColor", ref backgroundColor))
			{
				this.BackgroundColor = backgroundColor;
			}
			Color value;
			if (base.TryGetStyleProperty<Color>("foregroundColor", ref value))
			{
				this.ForegroundColor = new Color?(value);
			}
		}

		// Token: 0x17000255 RID: 597
		// (get) Token: 0x06000BDB RID: 3035 RVA: 0x000116AC File Offset: 0x0000F8AC
		[Nullable(0)]
		private PanelContainer Panel
		{
			[NullableContext(0)]
			get
			{
				return base.FindControl<PanelContainer>("Panel");
			}
		}

		// Token: 0x17000256 RID: 598
		// (get) Token: 0x06000BDC RID: 3036 RVA: 0x000447F5 File Offset: 0x000429F5
		[Nullable(0)]
		private Label OptionName
		{
			[NullableContext(0)]
			get
			{
				return base.FindControl<Label>("OptionName");
			}
		}

		// Token: 0x17000257 RID: 599
		// (get) Token: 0x06000BDD RID: 3037 RVA: 0x00044802 File Offset: 0x00042A02
		[Nullable(0)]
		private Label OptionDescription
		{
			[NullableContext(0)]
			get
			{
				return base.FindControl<Label>("OptionDescription");
			}
		}

		// Token: 0x06000BDE RID: 3038 RVA: 0x00044810 File Offset: 0x00042A10
		static void xaml(IServiceProvider A_0, PDASettingsButton A_1)
		{
			XamlIlContext.Context<PDASettingsButton> context = new XamlIlContext.Context<PDASettingsButton>(A_0, null, "resm:Content.Client.PDA.PDASettingsButton.xaml?assembly=Content.Client");
			context.RootObject = A_1;
			context.IntermediateRoot = A_1;
			A_1.HorizontalExpand = true;
			A_1.MinHeight = 48f;
			A_1.Margin = new Thickness(5f, 4f, 6f, 0f);
			PanelContainer panelContainer = new PanelContainer();
			panelContainer.Name = "Panel";
			Control control = panelContainer;
			context.RobustNameScope.Register("Panel", control);
			control = panelContainer;
			A_1.XamlChildren.Add(control);
			BoxContainer boxContainer = new BoxContainer();
			boxContainer.Orientation = 1;
			boxContainer.HorizontalExpand = true;
			boxContainer.VerticalExpand = true;
			boxContainer.Margin = new Thickness(8f, 4f, 0f, 4f);
			Label label = new Label();
			label.Name = "OptionName";
			control = label;
			context.RobustNameScope.Register("OptionName", control);
			control = label;
			boxContainer.XamlChildren.Add(control);
			Label label2 = new Label();
			label2.Name = "OptionDescription";
			control = label2;
			context.RobustNameScope.Register("OptionDescription", control);
			control = label2;
			boxContainer.XamlChildren.Add(control);
			control = boxContainer;
			A_1.XamlChildren.Add(control);
			if ((control = (A_1 as Control)) != null)
			{
				context.RobustNameScope.Absorb(control.NameScope);
				control.NameScope = context.RobustNameScope;
			}
			context.RobustNameScope.Complete();
		}

		// Token: 0x06000BDF RID: 3039 RVA: 0x000449D2 File Offset: 0x00042BD2
		private static void !XamlIlPopulateTrampoline(PDASettingsButton A_0)
		{
			PDASettingsButton.Populate:Content.Client.PDA.PDASettingsButton.xaml(null, A_0);
		}

		// Token: 0x040005B0 RID: 1456
		public const string StylePropertyFgColor = "foregroundColor";

		// Token: 0x040005B1 RID: 1457
		public const string StylePropertyBgColor = "backgroundColor";

		// Token: 0x040005B2 RID: 1458
		public const string NormalBgColor = "#313138";

		// Token: 0x040005B3 RID: 1459
		public const string HoverColor = "#3E6C45";

		// Token: 0x040005B4 RID: 1460
		public const string PressedColor = "#3E6C45";

		// Token: 0x040005B5 RID: 1461
		public const string DisabledFgColor = "#5a5a5a";

		// Token: 0x040005B6 RID: 1462
		public const string EnabledFgColor = "#FFFFFF";

		// Token: 0x040005B7 RID: 1463
		private readonly StyleBoxFlat _styleBox = new StyleBoxFlat
		{
			BackgroundColor = Color.FromHex("#252525", null)
		};
	}
}
