using System;
using System.Runtime.CompilerServices;
using CompiledRobustXaml;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Maths;

namespace Content.Client.Paper.UI
{
	// Token: 0x020001F1 RID: 497
	[GenerateTypedNameReferences]
	public sealed class StampWidget : Container
	{
		// Token: 0x1700028F RID: 655
		// (get) Token: 0x06000CB4 RID: 3252 RVA: 0x0004A459 File Offset: 0x00048659
		// (set) Token: 0x06000CB5 RID: 3253 RVA: 0x0004A466 File Offset: 0x00048666
		[Nullable(2)]
		public string Stamper
		{
			[NullableContext(2)]
			get
			{
				return this.StampedByLabel.Text;
			}
			[NullableContext(2)]
			set
			{
				this.StampedByLabel.Text = value;
			}
		}

		// Token: 0x06000CB6 RID: 3254 RVA: 0x0004A474 File Offset: 0x00048674
		public StampWidget()
		{
			StampWidget.!XamlIlPopulateTrampoline(this);
		}

		// Token: 0x17000290 RID: 656
		// (get) Token: 0x06000CB7 RID: 3255 RVA: 0x0004A482 File Offset: 0x00048682
		private Label StampedByLabel
		{
			get
			{
				return base.FindControl<Label>("StampedByLabel");
			}
		}

		// Token: 0x06000CB8 RID: 3256 RVA: 0x0004A490 File Offset: 0x00048690
		static void xaml(IServiceProvider A_0, StampWidget A_1)
		{
			XamlIlContext.Context<StampWidget> context = new XamlIlContext.Context<StampWidget>(A_0, null, "resm:Content.Client.Paper.UI.StampWidget.xaml?assembly=Content.Client");
			context.RootObject = A_1;
			context.IntermediateRoot = A_1;
			A_1.HorizontalAlignment = 2;
			A_1.Margin = new Thickness(6f, 6f, 6f, 6f);
			BoxContainer boxContainer = new BoxContainer();
			boxContainer.Orientation = 1;
			PanelContainer panelContainer = new PanelContainer();
			panelContainer.PanelOverride = new StyleBoxFlat
			{
				BackgroundColor = StyleNano.DangerousRedFore
			};
			Control control = new Control
			{
				MinSize = new Vector2(3f, 3f)
			};
			panelContainer.XamlChildren.Add(control);
			control = panelContainer;
			boxContainer.XamlChildren.Add(control);
			Label label = new Label();
			label.Name = "StampedByLabel";
			control = label;
			context.RobustNameScope.Register("StampedByLabel", control);
			string item = "LabelHeadingBigger";
			label.StyleClasses.Add(item);
			label.FontColorOverride = new Color?(StyleNano.DangerousRedFore);
			label.Margin = new Thickness(12f, 6f, 12f, 6f);
			control = label;
			boxContainer.XamlChildren.Add(control);
			PanelContainer panelContainer2 = new PanelContainer();
			panelContainer2.PanelOverride = new StyleBoxFlat
			{
				BackgroundColor = StyleNano.DangerousRedFore
			};
			control = new Control
			{
				MinSize = new Vector2(3f, 3f)
			};
			panelContainer2.XamlChildren.Add(control);
			control = panelContainer2;
			boxContainer.XamlChildren.Add(control);
			control = boxContainer;
			A_1.XamlChildren.Add(control);
			if ((control = (A_1 as Control)) != null)
			{
				context.RobustNameScope.Absorb(control.NameScope);
				control.NameScope = context.RobustNameScope;
			}
			context.RobustNameScope.Complete();
		}

		// Token: 0x06000CB9 RID: 3257 RVA: 0x0004A691 File Offset: 0x00048891
		private static void !XamlIlPopulateTrampoline(StampWidget A_0)
		{
			StampWidget.Populate:Content.Client.Paper.UI.StampWidget.xaml(null, A_0);
		}
	}
}
