using System;
using CompiledRobustXaml;
using Content.Client.Administration.UI.CustomControls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Shared.IoC;
using Robust.Shared.Localization;

namespace Content.Client.Lobby.UI
{
	// Token: 0x0200025F RID: 607
	[GenerateTypedNameReferences]
	internal sealed class ObserveWarningWindow : DefaultWindow
	{
		// Token: 0x06000F92 RID: 3986 RVA: 0x0005DD38 File Offset: 0x0005BF38
		public ObserveWarningWindow()
		{
			base.Title = Loc.GetString("observe-warning-window-title");
			ObserveWarningWindow.!XamlIlPopulateTrampoline(this);
			IoCManager.InjectDependencies<ObserveWarningWindow>(this);
			this.ObserveButton.OnPressed += delegate(BaseButton.ButtonEventArgs _)
			{
				this.Close();
			};
			this.NevermindButton.OnPressed += delegate(BaseButton.ButtonEventArgs _)
			{
				this.Close();
			};
		}

		// Token: 0x17000359 RID: 857
		// (get) Token: 0x06000F93 RID: 3987 RVA: 0x0005DD96 File Offset: 0x0005BF96
		private Button NevermindButton
		{
			get
			{
				return base.FindControl<Button>("NevermindButton");
			}
		}

		// Token: 0x1700035A RID: 858
		// (get) Token: 0x06000F94 RID: 3988 RVA: 0x0005DDA3 File Offset: 0x0005BFA3
		private CommandButton ObserveButton
		{
			get
			{
				return base.FindControl<CommandButton>("ObserveButton");
			}
		}

		// Token: 0x06000F97 RID: 3991 RVA: 0x0005DDB0 File Offset: 0x0005BFB0
		static void xaml(IServiceProvider A_0, DefaultWindow A_1)
		{
			XamlIlContext.Context<DefaultWindow> context = new XamlIlContext.Context<DefaultWindow>(A_0, null, "resm:Content.Client.Lobby.UI.ObserveWarningWindow.xaml?assembly=Content.Client");
			context.RootObject = A_1;
			context.IntermediateRoot = A_1;
			BoxContainer boxContainer = new BoxContainer();
			boxContainer.Orientation = 1;
			Control control = new Label
			{
				Text = (string)new LocExtension("observe-warning-1").ProvideValue()
			};
			boxContainer.XamlChildren.Add(control);
			control = new Label
			{
				Text = (string)new LocExtension("observe-warning-2").ProvideValue()
			};
			boxContainer.XamlChildren.Add(control);
			BoxContainer boxContainer2 = new BoxContainer();
			boxContainer2.Orientation = 0;
			Button button = new Button();
			button.Name = "NevermindButton";
			control = button;
			context.RobustNameScope.Register("NevermindButton", control);
			button.Text = (string)new LocExtension("observe-nevermind").ProvideValue();
			button.SizeFlagsStretchRatio = 1f;
			control = button;
			boxContainer2.XamlChildren.Add(control);
			control = new Control
			{
				HorizontalExpand = true,
				SizeFlagsStretchRatio = 2f
			};
			boxContainer2.XamlChildren.Add(control);
			CommandButton commandButton = new CommandButton();
			commandButton.Command = "observe";
			commandButton.Name = "ObserveButton";
			control = commandButton;
			context.RobustNameScope.Register("ObserveButton", control);
			string item = "Caution";
			commandButton.StyleClasses.Add(item);
			commandButton.Text = (string)new LocExtension("observe-confirm").ProvideValue();
			commandButton.SizeFlagsStretchRatio = 1f;
			control = commandButton;
			boxContainer2.XamlChildren.Add(control);
			control = boxContainer2;
			boxContainer.XamlChildren.Add(control);
			control = boxContainer;
			A_1.XamlChildren.Add(control);
			if ((control = (A_1 as Control)) != null)
			{
				context.RobustNameScope.Absorb(control.NameScope);
				control.NameScope = context.RobustNameScope;
			}
			context.RobustNameScope.Complete();
		}

		// Token: 0x06000F98 RID: 3992 RVA: 0x0005DFF3 File Offset: 0x0005C1F3
		private static void !XamlIlPopulateTrampoline(ObserveWarningWindow A_0)
		{
			ObserveWarningWindow.Populate:Content.Client.Lobby.UI.ObserveWarningWindow.xaml(null, A_0);
		}
	}
}
