using System;
using System.Runtime.CompilerServices;
using CompiledRobustXaml;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Utility;

namespace Content.Client.Info
{
	// Token: 0x020002B9 RID: 697
	[GenerateTypedNameReferences]
	public sealed class InfoSection : BoxContainer
	{
		// Token: 0x06001197 RID: 4503 RVA: 0x00068AA6 File Offset: 0x00066CA6
		[NullableContext(1)]
		public InfoSection(string title, string text, bool markup = false)
		{
			InfoSection.!XamlIlPopulateTrampoline(this);
			this.SetText(title, text, markup);
		}

		// Token: 0x06001198 RID: 4504 RVA: 0x00068ABD File Offset: 0x00066CBD
		[NullableContext(1)]
		public void SetText(string title, string text, bool markup = false)
		{
			this.TitleLabel.Text = title;
			if (markup)
			{
				this.Content.SetMessage(FormattedMessage.FromMarkup(text.Trim()));
				return;
			}
			this.Content.SetMessage(text);
		}

		// Token: 0x170003C6 RID: 966
		// (get) Token: 0x06001199 RID: 4505 RVA: 0x00068AF1 File Offset: 0x00066CF1
		private Label TitleLabel
		{
			get
			{
				return base.FindControl<Label>("TitleLabel");
			}
		}

		// Token: 0x170003C7 RID: 967
		// (get) Token: 0x0600119A RID: 4506 RVA: 0x00068AFE File Offset: 0x00066CFE
		private RichTextLabel Content
		{
			get
			{
				return base.FindControl<RichTextLabel>("Content");
			}
		}

		// Token: 0x0600119B RID: 4507 RVA: 0x00068B0C File Offset: 0x00066D0C
		static void xaml(IServiceProvider A_0, BoxContainer A_1)
		{
			XamlIlContext.Context<BoxContainer> context = new XamlIlContext.Context<BoxContainer>(A_0, null, "resm:Content.Client.Info.InfoSection.xaml?assembly=Content.Client");
			context.RootObject = A_1;
			context.IntermediateRoot = A_1;
			A_1.Orientation = 1;
			Label label = new Label();
			label.Name = "TitleLabel";
			Control control = label;
			context.RobustNameScope.Register("TitleLabel", control);
			string item = "LabelHeading";
			label.StyleClasses.Add(item);
			control = label;
			A_1.XamlChildren.Add(control);
			RichTextLabel richTextLabel = new RichTextLabel();
			richTextLabel.Name = "Content";
			control = richTextLabel;
			context.RobustNameScope.Register("Content", control);
			control = richTextLabel;
			A_1.XamlChildren.Add(control);
			if ((control = (A_1 as Control)) != null)
			{
				context.RobustNameScope.Absorb(control.NameScope);
				control.NameScope = context.RobustNameScope;
			}
			context.RobustNameScope.Complete();
		}

		// Token: 0x0600119C RID: 4508 RVA: 0x00068C25 File Offset: 0x00066E25
		private static void !XamlIlPopulateTrampoline(InfoSection A_0)
		{
			InfoSection.Populate:Content.Client.Info.InfoSection.xaml(null, A_0);
		}
	}
}
