using System;
using CompiledRobustXaml;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Maths;

namespace Content.Client.UserInterface.Systems.Actions.Controls
{
	// Token: 0x020000CC RID: 204
	[GenerateTypedNameReferences]
	public sealed class ActionPageButtons : Control
	{
		// Token: 0x060005C1 RID: 1473 RVA: 0x0001F6A7 File Offset: 0x0001D8A7
		public ActionPageButtons()
		{
			ActionPageButtons.!XamlIlPopulateTrampoline(this);
		}

		// Token: 0x170000E2 RID: 226
		// (get) Token: 0x060005C2 RID: 1474 RVA: 0x0001F6B5 File Offset: 0x0001D8B5
		public TextureButton LeftArrow
		{
			get
			{
				return base.FindControl<TextureButton>("LeftArrow");
			}
		}

		// Token: 0x170000E3 RID: 227
		// (get) Token: 0x060005C3 RID: 1475 RVA: 0x0000F55B File Offset: 0x0000D75B
		public Label Label
		{
			get
			{
				return base.FindControl<Label>("Label");
			}
		}

		// Token: 0x170000E4 RID: 228
		// (get) Token: 0x060005C4 RID: 1476 RVA: 0x0001F6C2 File Offset: 0x0001D8C2
		public TextureButton RightArrow
		{
			get
			{
				return base.FindControl<TextureButton>("RightArrow");
			}
		}

		// Token: 0x060005C5 RID: 1477 RVA: 0x0001F6D0 File Offset: 0x0001D8D0
		static void xaml(IServiceProvider A_0, ActionPageButtons A_1)
		{
			XamlIlContext.Context<ActionPageButtons> context = new XamlIlContext.Context<ActionPageButtons>(A_0, null, "resm:Content.Client.UserInterface.Systems.Actions.Controls.ActionPageButtons.xaml?assembly=Content.Client");
			context.RootObject = A_1;
			context.IntermediateRoot = A_1;
			BoxContainer boxContainer = new BoxContainer();
			boxContainer.Orientation = 0;
			Control control = new Control
			{
				HorizontalExpand = true,
				SizeFlagsStretchRatio = 1f
			};
			boxContainer.XamlChildren.Add(control);
			TextureButton textureButton = new TextureButton();
			textureButton.TexturePath = "/Textures/Interface/Nano/left_arrow.svg.192dpi.png";
			textureButton.SizeFlagsStretchRatio = 1f;
			textureButton.Scale = new Vector2(0.5f, 0.5f);
			textureButton.HorizontalAlignment = 2;
			textureButton.VerticalAlignment = 2;
			textureButton.Name = "LeftArrow";
			control = textureButton;
			context.RobustNameScope.Register("LeftArrow", control);
			textureButton.Access = new AccessLevel?(0);
			control = textureButton;
			boxContainer.XamlChildren.Add(control);
			control = new Control
			{
				HorizontalExpand = true,
				SizeFlagsStretchRatio = 2f
			};
			boxContainer.XamlChildren.Add(control);
			Label label = new Label();
			label.Text = "1";
			label.SizeFlagsStretchRatio = 1f;
			label.Name = "Label";
			control = label;
			context.RobustNameScope.Register("Label", control);
			label.Access = new AccessLevel?(0);
			control = label;
			boxContainer.XamlChildren.Add(control);
			control = new Control
			{
				HorizontalExpand = true,
				SizeFlagsStretchRatio = 2f
			};
			boxContainer.XamlChildren.Add(control);
			TextureButton textureButton2 = new TextureButton();
			textureButton2.TexturePath = "/Textures/Interface/Nano/right_arrow.svg.192dpi.png";
			textureButton2.SizeFlagsStretchRatio = 1f;
			textureButton2.Scale = new Vector2(0.5f, 0.5f);
			textureButton2.HorizontalAlignment = 2;
			textureButton2.VerticalAlignment = 2;
			textureButton2.Name = "RightArrow";
			control = textureButton2;
			context.RobustNameScope.Register("RightArrow", control);
			textureButton2.Access = new AccessLevel?(0);
			control = textureButton2;
			boxContainer.XamlChildren.Add(control);
			control = new Control
			{
				HorizontalExpand = true,
				SizeFlagsStretchRatio = 1f
			};
			boxContainer.XamlChildren.Add(control);
			control = boxContainer;
			A_1.XamlChildren.Add(control);
			if ((control = (A_1 as Control)) != null)
			{
				context.RobustNameScope.Absorb(control.NameScope);
				control.NameScope = context.RobustNameScope;
			}
			context.RobustNameScope.Complete();
		}

		// Token: 0x060005C6 RID: 1478 RVA: 0x0001F9A8 File Offset: 0x0001DBA8
		private static void !XamlIlPopulateTrampoline(ActionPageButtons A_0)
		{
			ActionPageButtons.Populate:Content.Client.UserInterface.Systems.Actions.Controls.ActionPageButtons.xaml(null, A_0);
		}
	}
}
