using System;
using CompiledRobustXaml;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.UserInterface.Systems.Ghost.Controls.Roles
{
	// Token: 0x0200008A RID: 138
	[GenerateTypedNameReferences]
	public sealed class GhostRoleEntryButtons : BoxContainer
	{
		// Token: 0x17000087 RID: 135
		// (get) Token: 0x06000331 RID: 817 RVA: 0x00013B84 File Offset: 0x00011D84
		public Button RequestButton
		{
			get
			{
				return base.FindControl<Button>("RequestButton");
			}
		}

		// Token: 0x17000088 RID: 136
		// (get) Token: 0x06000332 RID: 818 RVA: 0x00013B91 File Offset: 0x00011D91
		public Button FollowButton
		{
			get
			{
				return base.FindControl<Button>("FollowButton");
			}
		}

		// Token: 0x06000333 RID: 819 RVA: 0x00013B9E File Offset: 0x00011D9E
		public GhostRoleEntryButtons()
		{
			GhostRoleEntryButtons.!XamlIlPopulateTrampoline(this);
		}

		// Token: 0x06000334 RID: 820 RVA: 0x00013BAC File Offset: 0x00011DAC
		static void xaml(IServiceProvider A_0, BoxContainer A_1)
		{
			XamlIlContext.Context<BoxContainer> context = new XamlIlContext.Context<BoxContainer>(A_0, null, "resm:Content.Client.UserInterface.Systems.Ghost.Controls.Roles.GhostRoleEntryButtons.xaml?assembly=Content.Client");
			context.RootObject = A_1;
			context.IntermediateRoot = A_1;
			A_1.Orientation = 0;
			Button button = new Button();
			button.Name = "RequestButton";
			Control control = button;
			context.RobustNameScope.Register("RequestButton", control);
			button.Access = new AccessLevel?(0);
			button.Text = (string)new LocExtension("ghost-roles-window-request-role-button").ProvideValue();
			string item = "OpenRight";
			button.StyleClasses.Add(item);
			button.HorizontalAlignment = 1;
			control = button;
			A_1.XamlChildren.Add(control);
			Button button2 = new Button();
			button2.Name = "FollowButton";
			control = button2;
			context.RobustNameScope.Register("FollowButton", control);
			button2.Access = new AccessLevel?(0);
			button2.Text = (string)new LocExtension("ghost-roles-window-follow-role-button").ProvideValue();
			item = "OpenLeft";
			button2.StyleClasses.Add(item);
			button2.HorizontalAlignment = 3;
			control = button2;
			A_1.XamlChildren.Add(control);
			if ((control = (A_1 as Control)) != null)
			{
				context.RobustNameScope.Absorb(control.NameScope);
				control.NameScope = context.RobustNameScope;
			}
			context.RobustNameScope.Complete();
		}

		// Token: 0x06000335 RID: 821 RVA: 0x00013D4B File Offset: 0x00011F4B
		private static void !XamlIlPopulateTrampoline(GhostRoleEntryButtons A_0)
		{
			GhostRoleEntryButtons.Populate:Content.Client.UserInterface.Systems.Ghost.Controls.Roles.GhostRoleEntryButtons.xaml(null, A_0);
		}
	}
}
